COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/region.tbl'    USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/nation.tbl'    USING DELIMITERS '|', '|\n';
COPY     1000000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/supplier.tbl'  USING DELIMITERS '|', '|\n';
COPY    15000000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/customer.tbl'  USING DELIMITERS '|', '|\n';
COPY    20000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/part.tbl'      USING DELIMITERS '|', '|\n';
COPY    80000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/partsupp.tbl'  USING DELIMITERS '|', '|\n';
COPY   150000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/orders.tbl'    USING DELIMITERS '|', '|\n';
COPY   600037902 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-100>/lineitem.tbl'  USING DELIMITERS '|', '|\n';
