COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/region.tbl'    USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/nation.tbl'    USING DELIMITERS '|', '|\n';
COPY     3000000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/supplier.tbl'  USING DELIMITERS '|', '|\n';
COPY    45000000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/customer.tbl'  USING DELIMITERS '|', '|\n';
COPY    60000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/part.tbl'      USING DELIMITERS '|', '|\n';
COPY   240000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/partsupp.tbl'  USING DELIMITERS '|', '|\n';
COPY   450000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/orders.tbl'    USING DELIMITERS '|', '|\n';
COPY  1799989091 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-300>/lineitem.tbl'  USING DELIMITERS '|', '|\n';
