COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/region.tbl'   USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/nation.tbl'   USING DELIMITERS '|', '|\n';
COPY    10000000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/supplier.tbl' USING DELIMITERS '|', '|\n';
COPY   150000000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/customer.tbl' USING DELIMITERS '|', '|\n';
COPY   200000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/part.tbl'     USING DELIMITERS '|', '|\n';
COPY   800000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/partsupp.tbl' USING DELIMITERS '|', '|\n';
COPY  1500000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/orders.tbl'   USING DELIMITERS '|', '|\n';
COPY  5999989709 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-1000>/lineitem.tbl' USING DELIMITERS '|', '|\n';
