COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/region.tbl'     USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/nation.tbl'     USING DELIMITERS '|', '|\n';
COPY      100000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/supplier.tbl'   USING DELIMITERS '|', '|\n';
COPY     1500000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/customer.tbl'   USING DELIMITERS '|', '|\n';
COPY     2000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/part.tbl'       USING DELIMITERS '|', '|\n';
COPY     8000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/partsupp.tbl'   USING DELIMITERS '|', '|\n';
COPY    15000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/orders.tbl'     USING DELIMITERS '|', '|\n';
COPY    59986052 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-10>/lineitem.tbl'   USING DELIMITERS '|', '|\n';
