COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/region.tbl'     USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/nation.tbl'     USING DELIMITERS '|', '|\n';
COPY      300000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/supplier.tbl'   USING DELIMITERS '|', '|\n';
COPY     4500000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/customer.tbl'   USING DELIMITERS '|', '|\n';
COPY     6000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/part.tbl'       USING DELIMITERS '|', '|\n';
COPY    24000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/partsupp.tbl'   USING DELIMITERS '|', '|\n';
COPY    45000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/orders.tbl'     USING DELIMITERS '|', '|\n';
COPY   179998372 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-30>/lineitem.tbl'   USING DELIMITERS '|', '|\n';
