COPY           5 RECORDS INTO region   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/region.tbl'   USING DELIMITERS '|', '|\n';
COPY          25 RECORDS INTO nation   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/nation.tbl'   USING DELIMITERS '|', '|\n';
COPY    30000000 RECORDS INTO supplier FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/supplier.tbl' USING DELIMITERS '|', '|\n';
COPY   450000000 RECORDS INTO customer FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/customer.tbl' USING DELIMITERS '|', '|\n';
COPY   600000000 RECORDS INTO part     FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/part.tbl'     USING DELIMITERS '|', '|\n';
COPY  2400000000 RECORDS INTO partsupp FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/partsupp.tbl' USING DELIMITERS '|', '|\n';
COPY  4500000000 RECORDS INTO orders   FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/orders.tbl'   USING DELIMITERS '|', '|\n';
COPY 18000048306 RECORDS INTO lineitem FROM '/<REPLACE_WITH_ABSOLUTE_PATH_TO_DATA_FILES_FOR_SF-3000>/lineitem.tbl' USING DELIMITERS '|', '|\n';
